nfl_api_base_url = "https://api.sportsdata.io/v3/nfl"
nfl_teams_url = "https://api.sportsdata.io/v3/nfl/scores/json/Teams"
nfl_standings_url = "https://api.sportsdata.io/v3/nfl/scores/json/Standings/{season}"
nfl_schedules_url = "https://api.sportsdata.io/v3/nfl/scores/json/Schedules/{season}"
nfl_scores_url = "https://api.sportsdata.io/v3/nfl/scores/json/ScoresByWeek/{season}/{week}"
nfl_team_stats_url = "https://api.sportsdata.io/v3/nfl/stats/json/TeamSeasonStats/{season}"

[get-nfl-data]
    [get-nfl-data.2019]
        start_week = 1
        end_week = 17
        season_type = "REG"
        
    [get-nfl-data.2020]
        start_week = 1
        end_week = 17
        season_type = "REG"
        
    [get-nfl-data.2021]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [get-nfl-data.2022]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [get-nfl-data.2023]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [get-nfl-data.2024]
        start_week = 1
        end_week = 18
        season_type = "REG"

[get-nfl-odds-data]
    [get-nfl-odds-data.2023]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [get-nfl-odds-data.2024]
        start_week = 1
        end_week = 18
        season_type = "REG"

[create-nfl-games]
    [create-nfl-games.2019]
        start_week = 1
        end_week = 17
        season_type = "REG"
        
    [create-nfl-games.2020]
        start_week = 1
        end_week = 17
        season_type = "REG"
        
    [create-nfl-games.2021]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [create-nfl-games.2022]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [create-nfl-games.2023]
        start_week = 1
        end_week = 18
        season_type = "REG"
        
    [create-nfl-games.2024]
        start_week = 1
        end_week = 18
        season_type = "REG"
